from app.retrieval.retriever import retrieve_and_rerank

from app.rag.generator import generate_answer

from app.rag.citations import (
    build_citation_map,
    extract_citation_ids,
    validate_citations,
)

from app.rag.validators import (
    validate_answer,
)


def run_rag(question: str) -> dict:
    """
    Complete RAG pipeline:

    Query
      ↓
    Retrieval
      ↓
    Reranking
      ↓
    Context building
      ↓
    Prompt
      ↓
    LLM
      ↓
    Validation
      ↓
    Citation extraction
    """

    # -----------------------------------------
    # 1. RETRIEVAL + RERANKING
    # -----------------------------------------

    documents = retrieve_and_rerank(
        question
    )

    if not documents:
        return {
            "answer": (
                "I could not find relevant information "
                "in the available documents."
            ),
            "citations": [],
        }

    # -----------------------------------------
    # 2. BUILD CITATION MAP
    # -----------------------------------------

    citation_map = build_citation_map(
        documents
    )

    # -----------------------------------------
    # 3. GENERATE ANSWER
    # -----------------------------------------

    answer = generate_answer(
        question=question,
        documents=documents,
    )

    # -----------------------------------------
    # 4. VALIDATE ANSWER
    # -----------------------------------------

    answer = validate_answer(answer)

    # -----------------------------------------
    # 5. EXTRACT CITATIONS
    # -----------------------------------------

    citation_ids = extract_citation_ids(
        answer
    )

    # -----------------------------------------
    # 6. VALIDATE CITATIONS
    # -----------------------------------------

    invalid_citations = validate_citations(
        answer,
        citation_map,
    )

    if invalid_citations:
        raise ValueError(
            "Invalid citations generated by the LLM: "
            f"{invalid_citations}"
        )

    # -----------------------------------------
    # 7. RESOLVE CITATIONS
    # -----------------------------------------

    citations = []

    for citation_id in citation_ids:

        if citation_id not in citations:

            citations.append(
                citation_id
            )

    resolved_citations = [
        {
            "id": citation_id,
            **citation_map[citation_id],
        }
        for citation_id in citations
    ]

    return {
        "answer": answer,
        "citations": resolved_citations,
        "prompt_version": "v1",
    }


def main():

    question = (
        "What were the major features "
        "of Mauryan administration?"
    )

    result = run_rag(question)

    print("\n" + "=" * 80)
    print("QUESTION")
    print("=" * 80)

    print(question)

    print("\n" + "=" * 80)
    print("ANSWER")
    print("=" * 80)

    print(result["answer"])

    print("\n" + "=" * 80)
    print("CITATIONS")
    print("=" * 80)

    for citation in result["citations"]:

        print(
            f"[{citation['id']}] "
            f"{citation['source']} "
            f"(page {citation['page']})"
        )

    print(
        "\nPrompt version:",
        result["prompt_version"],
    )


if __name__ == "__main__":
    main()